name: Build N2N_IPV6

on:
#  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: ${{ matrix.TARGET }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows_static
            os: windows-latest
            ARCH: x64
            MSVC_ARCH: x64
          - target: x86_64-pc-windows
            os: windows-latest
            ARCH: x64
            MSVC_ARCH: x64

          - target: aarch64-linux-musl_static
            os: ubuntu-latest
            URL: aarch64-linux-musl
          - target: aarch64-linux-musl
            os: ubuntu-latest
            URL: aarch64-linux-musl

          - target: x86_64-linux-musl_static
            os: ubuntu-latest
            URL: x86_64-linux-musl
          - target: x86_64-linux-musl
            os: ubuntu-latest
            URL: x86_64-linux-musl

    runs-on: ${{ matrix.os }}
    env:
      TARGET: ${{ matrix.TARGET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Generate Artifact Name
        shell: bash
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          ARCH_PART=$(echo "${{ matrix.TARGET }}" | cut -d'-' -f1)
          REST_PART=$(echo "${{ matrix.TARGET }}" | cut -d'-' -f2-)
          echo "ARTIFACT_NAME=n2n-${REST_PART}-${ARCH_PART}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Setup MSVC environment
        if: runner.os == 'windows'
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ${{ matrix.MSVC_ARCH }}

      - name: Windows build (static)
        if: runner.os == 'windows' && endsWith(matrix.TARGET, '_static')
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake .. `
            -G "NMake Makefiles" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_C_FLAGS_RELEASE="/MT /O2 /DWIN32 /D_WIN32_WINNT=0x0601" `
            -DCMAKE_EXE_LINKER_FLAGS="/SUBSYSTEM:CONSOLE,6.01 /MACHINE:${{ matrix.ARCH }}" `
            -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"
          nmake
          .\edge.exe -h || true
          .\supernode.exe -h || true

      - name: Windows build (dynamic)
        if: runner.os == 'windows' && !endsWith(matrix.TARGET, '_static')
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake .. `
            -G "NMake Makefiles" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_C_FLAGS_RELEASE="/MD /O2 /DWIN32 /D_WIN32_WINNT=0x0601" `
            -DCMAKE_EXE_LINKER_FLAGS="/SUBSYSTEM:CONSOLE,6.01 /MACHINE:${{ matrix.ARCH }}" `
            -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDLL"
          nmake
          .\edge.exe -h || true
          .\supernode.exe -h || true

      - name: Download gcc
        if: runner.os == 'Linux'
        uses: lmq8267/dl-musl@main
        with:
          target: ${{ matrix.URL }}
          static: true
          gccpath: /opt/musl_gcc

      - name: Linux build (static)
        if: runner.os == 'Linux' && endsWith(matrix.TARGET, '_static')
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS="-O2 -ffunction-sections -fdata-sections -fno-strict-aliasing" \
            -DCMAKE_EXE_LINKER_FLAGS="-static -Wl,--gc-sections -static-libgcc" \
            -DCMAKE_C_COMPILER=${CC}
          make -j$(nproc)
          ./edge -h || true
          ls -la
          file edge
          $STRIP edge
          $STRIP supernode

      - name: Linux build (dynamic)
        if: runner.os == 'Linux' && !endsWith(matrix.TARGET, '_static')
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS="-O2 -ffunction-sections -fdata-sections -fno-strict-aliasing" \
            -DCMAKE_EXE_LINKER_FLAGS="-Wl,--gc-sections" \
            -DCMAKE_C_COMPILER=${CC}
          make -j$(nproc)
          ./edge -h || true
          ls -la
          file edge
          $STRIP edge
          $STRIP supernode

      - name: Upload
        uses: actions/upload-artifact@master
        if: always()
        continue-on-error: true
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            build/edge${{ runner.os == 'Windows' && '.exe' || '' }}
            build/supernode${{ runner.os == 'Windows' && '.exe' || '' }}

      - name: Delete workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 2
          keep_minimum_runs: 0
